using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Afterglow.Core.Configuration
{
    [AttributeUsage(AttributeTargets.Property, Inherited = true, AllowMultiple = false)]
    public abstract class ConfigAttribute: Attribute
    {
        /// <summary>
        /// Display name for the configuration item
        /// </summary>
        public string DisplayName { get; set; }
        /// <summary>
        /// Describe how changing this value effects the plugin
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// The effects the order that the settings are shown Note: low numbers at the top and highg numbers at the bottom
        /// </summary>
        public int SortIndex { get; set; }
        /// <summary>
        /// Is this property hidden from the autogenerated screens
        /// </summary>
        public bool IsHidden { get; set; }
    }
}
